### ISSUE TITLE
Go SDK ListEnvironments() errors out with json: unknown field "tags"

### ISSUE THREAD

**Issue by pdemagny** [pulumi/esc-sdk#17]
### What happened?

Hi, we are Pulumi customers (on the Team plan) and I was trying to use ESC with the go SDK in conjunction with the Automation API, but even the simplest use case from [the SDK docs](https://www.pulumi.com/docs/esc/sdk/go/#manage-environment-example) does not seem to work.  
The `CreateEnvironment()` works, but the `ListEnvironments()` does not, which is blocking for I'm trying to do: _create an environment, but only if it does not already exists !_

### Example

Reproducing is pretty easy:

I have 2 extremely simple environments only for testing purpose, one created with the SDK's `CreateEnvironment()` that contains 1 config, and one created through the Pulumi Console that only contains 1 secret and imports the other environment.  

Just use the code snippet from the SDK docs:

```golang
	configuration := esc.NewConfiguration()
	escClient := esc.NewClient(configuration)
	authCtx := esc.NewAuthContext(pulumiAccessToken)

	orgEnvs, err := escClient.ListEnvironments(authCtx, orgName, nil)
	if err != nil {
		log.Fatalf("Failed to list environments: %v", err)
	}

	for _, orgEnv := range orgEnvs.Environments {
		log.Printf("Environment: %v\n", orgEnv.Name)
	}
```

**`2024/07/19 12:21:34 Failed to list environments: json: unknown field "tags"`**

### Output of `pulumi about`

github.com/pulumi/esc-sdk/sdk v0.9.1

❯ pulumi about
CLI          
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pdemagny-blobr
User           pdemagny-blobr
Organizations  pdemagny-blobr, blobr-io, blobr-ai
Token type     personal

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cleverguy25** [comment]
@pdemagny I will look into this later today, sorry you are hitting this!

**Comment by cleverguy25** [comment]
@pdemagny Sorry a new change causes a regression, only in the SDK.  A new version is published now that should fix your issue.
